name: Kotlin CI CD with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: use JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: gradlew Full Authorization
        run: chmod 777 gradlew

      - name: Test::test
        run: ./gradlew test

      - name: Clean and Build
        run: ./gradlew clean build -x test
  CD:
    runs-on: ubuntu-latest
    needs: CI

    steps:
      - uses: actions/checkout@v2
  
      - name: use JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: gradlew Full Authorization
        run: chmod 777 gradlew

      - name: Clean and Build
        run: ./gradlew clean build -x test

      - name: Create Docker Image
        run: docker build --tag hwanghae .

      - name: Upload to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: 0816jinjin/hwanghae
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
